### ISSUE TITLE
Generating a list of base applications 

### ISSUE THREAD

**Issue by mpaskevi** [maryi/CSCW-Project#11]
We should consider building a base list of apps for the database.  This should not be a problem and there are lists available online as well (see: https://en.wikipedia.org/wiki/List_of_collaborative_software).  What I am more concerned with is, how do we want to describe each app in the database?  What fields should we collect which will help us describe the apps and help us connect them to the MoCA framework?  Or perhaps we need to enter the 1-10 rating for the seven dimensions for each app?  The lists in wikipedia have some examples of data structures, eg. creator, web based vs downloadable, database backend, purpose of use, etc.  

We can start populating a google spreadsheet with the list of apps and associated descriptors.  I will spin this up after the proposal is complete.

**Comment by maryi** [comment]
I thought about the same thing @mpaskevi when I saw the title of this issue.. i have a couple of apps that could go into our database, but how to "rate" them based on the MoCA framework?
We kinda started with a solution for that when we design the app mockups. For example, when asking about the number of people supported by the tool I consider 2, 4, 20 and N because I thought those were the usual limits. However, we still have different ideas about how to classify a tool in the Planned permanence dimension (issue #9). So we definetly need to go over this together and make some agreements.

**Comment by maryi** [comment]
Progress on this area is being reported here #17 .. so, I'm closing this issue
