### ISSUE TITLE
Project presentation powerpoint

### ISSUE THREAD

**Issue by kristalow** [maryi/CSCW-Project#26]
Link to this week's presentation:
https://docs.google.com/presentation/d/1e0ToTf57v-narrA592b5_1DN9x0KgVXUhrFSOw02BQE/edit?usp=sharing 

from slack:
"For this project update, you should prepare 3-5 slides, and speak for 5-10(max) minutes to discuss work done so far, next milestones and hurdles faced."

**Comment by kristalow** [comment]
feel free to add/change anything on the slides..
if anyone has any hurdles/challenges they've come across so far, feel free to add them to the slide

**Comment by mpaskevi** [comment]
@dustinfaulkner91  could you please ensure we are able to show the website during the presentation today?  I currently do not see a 'link to' or a 'screenshot of' the website in the presentation.   

@eli4 It might also be useful to have a screenshot of the database.  Also might be nice to reflect on the challenge of finding a place to host our database.  

We have the descriptors spreadsheet linked in the presentation so that can be brought up for a brief discussion.

**Comment by eli4** [comment]
I'm not 100% sure what you mean when you say you want a screenshot of the database. If you want the code for the database it is now in the repository under the directory development/database. If you wanted a description of where the database is hosted: https://aws.amazon.com/ec2/

**Comment by mpaskevi** [comment]
Presentation done, well done!
