### ISSUE TITLE
List of app requirements

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#8]
Help to create the list of requirements

**Comment by maryi** [comment]
1. User can register and create an account on the application (?)
**I think we need to be able to create user accounts in order to track what tools users use in conjuction with others. Then, if a user can register in the system, he/she should be able to 
2. Log in to the app
3. Log out of the app

**Comment by dustinfaulkner91** [comment]
I think if we make personal log ins it takes away from what we are trying to achieve. Is there another way that we can figure out what people are using together? Just because a user had a an app in their list does not mean that it was used with others. 
I thought we wanted everyone to be able to rate/see/add apps.

**Comment by maryi** [comment]
Hi @dustinfaulkner91,
I agree with you... you made me think that if we really want to make our app of "easy access" we shouldn't be putting the registration extra step. However, I don't know how are we going to be able to say that an app is complementary of another one is we don't have information from user sessions.. are you thinking about a voting system or something similar?

**Comment by maryi** [comment]
I think we already have the user requirements well defined in the interim report. Closing issue.
